### PR TITLE
Use GNU coreutils (tr, sed) rather than sd.

### PR DESCRIPTION
**Pull request by josuer08**
The changes implemented here are just so everyone can run this script without installing extra packages

### CODE REVIEW

**Comment by josuer08** [comment]
@coolaj86 this is just a small change that can or cannot be implemented according to your criteria but I think could be helpful to some

**Comment by coolaj86** [comment]
The problem with `sed` is that it _isn't_ standard. Otherwise I would have used it.

GNU `sed` and BSD `sed` are incompatible in unhelpful, but frustrating ways. `sd` is the same on all platforms.

I was under the impression that the perl-style regexp in `grep`, meaning `\<` for start -f-word-break-or-line would work everywhere. Using `.` is incorrect because that will match _any_ character.

If this works in both GNU, BSD, and Darwin `sed`, then it's fine by me to switch - I just didn't want to take the time to test it.

**Comment by josuer08** [comment]
Ok I'll go ahead and test it out, but no, \. The way it was written does
not work everywhere. I'll arrive at a more universal one if I can, one that
does not need extra software, let's see what happens.

**Comment by coolaj86** [comment]
> `\.` The way it was written does not work everywhere.

Are you sure you just hadn't tried it with double quotes? If you use double quotes it will try to escape it as a bash sequence, not as a grep regexp.

**Comment by coolaj86** [comment]
@josuer08 What did you discover?

**Pull request closed without merging**
